name: .NET Core

on:
  push:
    branches:
  pull_request:
  workflow_dispatch:

jobs:
  comment:
    uses: ./.github/workflows/comment.yml

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Show variables
      run: |
        echo "github.event_name: ${{ github.event_name }}"
        echo "github.event.action: ${{ github.event.action }}"
        echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
        echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
        echo "github: ${{ toJson(github) }}"
    - name: Show env vars related to GitVersion
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
    - name: Override GITHUB_REF in PRs
      run: |
        # When the workflow is triggered by a pull request event, the ref is on the format refs/pull/123/merge.
        # This causes GitVersion to create a version based on the merge branch instead of the PR head branch, on the format 3.2.1-PullRequest0123.1.
        echo "GITHUB_REF=${{ github.event.pull_request.head.ref || github.ref }}"
        echo "GITHUB_REF=${{ github.event.pull_request.head.ref || github.ref }}" >> $GITHUB_ENV
    - name: Show env vars related to GitVersion (After override)
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Show env vars related to GitVersion (with step override)
      env:
        GITHUB_REF: ${{ github.event.pull_request.head.ref || github.ref }}
        RAI_RAI: "VOI-VOI"
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "RAI_RAI: $RAI_RAI"
    - uses: gittools/actions/gitversion/setup@v1.1.0
      with:
        versionSpec: '5.x'
    - uses: gittools/actions/gitversion/command@v1.1.0
      with:
        arguments: "-b ${{ github.event.pull_request.head.ref || github.ref }}"
    - name: Show SHA
      run: |
        SHA="${{ github.event.pull_request.head.sha || github.sha }}"
        echo "SHA: $SHA"
        SHORT_SHA=$(git rev-parse --short $SHA)
        echo "SHORT_SHA: $SHORT_SHA"
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
