name: .NET Core

on:
  push:
    branches:
  pull_request:
  workflow_dispatch:

jobs:
  comment:
    uses: ./.github/workflows/comment.yml

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Show variables
      run: |
        echo "github.event_name: ${{ github.event_name }}"
        echo "github.event.action: ${{ github.event.action }}"
        echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
        echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
        echo "github: ${{ toJson(github) }}"
    - name: Show env vars related to GitVersion
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
    - uses: actions/checkout@v2
    - name: Show SHA
      run: |
        SHA="${{ github.event.pull_request.head.sha || github.sha }}"
        echo "SHA: $SHA"
        SHORT_SHA=$(git rev-parse --short $SHA)
        echo "SHORT_SHA: $SHORT_SHA"
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
